config/routes.rb
Rails.application.routes.draw do
  resources :notes
  devise_for :users
  resources :users, only: :show
  resources :seminars do
    resources :articles,only: [:create,:update,:delete, :edit]
      collection do
        get 'search'
      end
    end
  root 'seminars#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  belongs_to :seminar
end

app/models/note.rb
class Note < ActiveRecord::Base
end

app/models/seminar.rb
class Seminar < ActiveRecord::Base
  belongs_to :user
  has_many :articles
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar,
                    styles: { medium:"300x300#", thumb:"100x100#"}
  validates_attachment_content_type :avatar,
                                        content_type:["image/jpg","image/jpeg","image/png"]
  has_many :articles
  has_many :seminars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

    def after_sign_out_path_for(resource)
      '/users/sign_in' # サインアウト後のリダイレクト先URL
    end

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys:[:nickname, :avatar, :affliation])
    end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Articles.all
  end

  def create
    @seminar = Seminar.find(params[:seminar_id])
    @article = Article.create(article_params)
    redirect_to seminar_path(@seminar)
  end

  def update
      article = Article.find(params[:id])
  end

  private
  def article_params
    params.require(:article).permit(:comment).merge(seminar_id: params[:seminar_id])
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :text)
    end
end

app/controllers/seminars_controller.rb
class SeminarsController < ApplicationController
  before_action :authenticate_user!, except: [:index,:search]

  def index
    @seminars= Seminar.order('created_at DESC').page(params[:page]).per(6)
  end

  def show
    @seminar = Seminar.find(params[:id])
    @articles= @seminar.articles.all
    @article = Article.new
    @name = current_user
  end

  def new
    @seminar = Seminar.new
  end

  def create
   Seminar.create(seminar_params)
  end

  def edit
  end

  def update
    seminar = Seminar.find(params[:id])
  end

  def destroy
    seminar = Seminar.find(params:[id])
    seminar.delete if seminar.user_id == current_user.id
  end

  def search
    @seminar = Seminar.where('title LIKE(?)',"%#{params[:keyword]}%").order('created_at DESC').page(params[:page]).per(6)
  end

private
  def seminar_params
   params.require(:seminar).permit(:title,:concept,:photo_all,:participants,:num_ppl,:span,:intro_title,:intro,:body_title,:body,:ending_title,:ending,:facilitator,:facilitator_image,:background,:tips,:user_id,:time_table)
  end

  def seminar_id
    @seminar = Seminar.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/seminars_helper.rb
module SeminarsHelper
end

app/views/articles/create.js.erb
$('#comment_field').val('');
$('#comments').html(
  "<%= j(render partial: 'articles/article', collection: @seminar.articles, locals: {@article: article}) %>"
);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>WSReciepe</title>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
<%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/seminars"><h3><strong>WS_reciepe</strong></h3></a>
      </div>
              <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"></a>
           <li class="dropdown">
               <div class="navbar-form navbar-left clearfix", role="search">
               <div class="form-group-search" style="float:left">
               <% if user_signed_in? %>
               <%=form_tag('/seminars/search', method: :get)do%>
               <input type="text" class="form-control" placeholder="Search" name="keyword">
          </div><button type="submit" class="btn btn-default">検索</button>
              <% end %>
            <%end%>
            </li>
          </li>
        </ul>


      <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="navbar-brand">
          <ul><%= form_tag("/users/sign_in", method: :get, class: "navbar_right")do%>
           <input type="submit", value="ログインする" >
           <%end%>
           </ul>
      </div>
      <div class="navbar-brand">
          <ul><%= form_tag("/users/sign_out", method: :delete, class: "navbar_right")do%>
           <input type="submit", value="ログアウトする" >
           <%end%>
          </ul>
        </div>
        <ul>
    <div class="navbar-brand">
          <ul><%= form_tag("/seminars/new", method: :get, class: "navbar_right")do%>
           <input type="submit", value="ワークショップを投稿する" >
           <%end%>
          </ul>
        </div>
        <ul>

     </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
  </nav>

  <%= yield %>

</body>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.text %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Text:</strong>
  <%= @note.text %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/seminars/_information.html.erb
<div>
  <div>
  </div>
</div>

app/views/seminars/_search_result.html.erb
<div class="entrylist" clearfix>
      <dl class="entrylistset">
        <dt class="entrylist_l">
          <a href="http://www.ashita-lab.jp/special/7758/">
                          <img width="160" height="160" src="http://www.ashita-lab.jp/wp-content/uploads/2017/04/170331_sxsw_tmb-160x160.jpg" class="image_result" alt="" srcset="http://www.ashita-lab.jp/wp-content/uploads/2017/04/170331_sxsw_tmb-160x160.jpg 160w, http://www.ashita-lab.jp/wp-content/uploads/2017/04/170331_sxsw_tmb-60x59.jpg 60w, http://www.ashita-lab.jp/wp-content/uploads/2017/04/170331_sxsw_tmb.jpg 300w, http://www.ashita-lab.jp/wp-content/uploads/2017/04/170331_sxsw_tmb-200x200.jpg 200w" sizes="(max-width: 160px) 100vw, 160px">
                      </a>
        </dt>
        <dd class="entrylist_r">
          <dl>
            <dt><a id=seminar_title_search  href="
            /seminars/<%=seminar.id%>"><%=seminar.title%></a>
            </dt>
                  <br /><dd class="date"><%=seminar.created_at%></dd>
                  <dd class="txt">
                  <p class="concept_search"><%=seminar.concept%></p>
                  <span><%= link_to "続きを読む",seminar_path(seminar), method: :get %></span>
            </dd>
          </dl>
        </dd>
      </dl>
<div class="entrysnsset">
        <ul class="sns-menu">
        </ul>
    </div>
</div>

app/views/seminars/_seminar.html.erb
<div class="entrylist_right">
  <div class="attachment">
    <img class="article_photo" alt="no image"><%= image_tag seminar.photo_file_name%>
        <div class="entlyst_text">
         <a class="entry_seminar_title" href='/seminars/<%=seminar.id%>'><%=seminar.title%></a>
        </div>
  </div>
</div>

app/views/seminars/create.html.erb
<div class="uplode done">
  <h>投稿が完了しました</h>
  <%= form_tag('/seminars', method: :get) do%>
    <input type="submit" value="一覧へ戻る">
  <% end%>
</div>

app/views/seminars/destroy.html.erb
  <div class="contents row">
    <div class="success">
      <h3>
        削除が完了しました。
      </h3>
      <a class="btn" href="/seminars">投稿一覧へ戻る</a>
    </div>
  </div>

app/views/seminars/index.html.erb
<header>
<div id="contents">
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img src="http://ict-enews.net/wp-content/uploads/2016/11/main-58.jpg" width="800px" height="499px" alt="ようこそ">
     <div class="container">
            <div class="carousel-caption" font-family="">
              <h1>[小学生徒対象]RPGを作ってプログラミングを学ぼう!!<h1>
              <p>2016/11 日比谷公会堂<code></code></p>
              <p><a class= href= role="button"></a></p>
            </div>
          </div>
      <div class="carousel-caption">
        ...
      </div>
    </div>
    <div class="item">
      <img src="http://www.xrite.co.jp/images/March_eXact_WS2.jpg" alt="..." width="800px" height="300px">
      <div class="carousel-caption">
        ...

      </div>
    </div>
    ...
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <img class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</header>

<body background="../assets/paper_tex.jpg">
  <div class="contentsset clearfix">
    <div class="articles_index">
     <h3 class="page-header-index"><strong>Recent Entries</strong><br />~最新の投稿~</h3>
        <%@seminars.each do |seminar|%>
          <%= render partial:"seminar", locals:{ seminar:seminar}%><%end%>
      </div>
      <div class="widegets">
          <div class="info">
          <h3 class="side-header"><strong>Information</strong><br />~お知らせ~</h3>
        <%@seminars.each do |seminar|%>
          <%= render partial:"information", locals:{ seminar:seminar}%><%end%>
          </div>
          <div class="remark_tag">
          <h3 class="side-header">
              <strong>Hot Keywords</strong><br />~注目のキーワード~</h3>
          </div>
          </div>
      <%= paginate(@seminars) %>
      </div>
  </div>

<footer>ALL RIGHT RESERVED WS_reciepe (C)
</footer>

  </body>
  </html>

app/views/seminars/new.html.erb
<body background="../assets/paper_tex.jpg">
<h3 class="page-header_input"><i><strong>ワークショップの投稿</strong></i></h3>
<div class="content">
  <div class="middle_content">
    <%= form_for [@seminar] do |f|%>
           <div class="container clearfix">
              <div class="contentsset">
                <div class="column_head">
                    <div class="article_seminar">
                    <div class="seminar_title">
                      <div>
                        <h2>
                        <%=f.text_field :title, placeholder: "タイトル" %>
                        </h2>
                      </div>
                      <%=f.label :ジャンルを選択してください%>
                              <select>
                                        <option value="art">アート系</option>
                                        <option value="local">まちづくり系</option>
                                        <option value="social_change">社会変革系</option>
                                        <option value="nature">自然・環境系</option>
                                        <option value="education">教育・学習系</option>
                                        <option value="spritual">精神世界系</option>
                                        <option value="mixture">統合系</option>
                            </select>
                    </div>

                    <p class="timestamp"><%= @seminar.created_at%><br /></p>
                        <div class="seminar_photo"><%= f.label :ワークショップの写真%><br />
                        <%= f.file_field :photo, :placeholder => "画像をアップロード"%>
                    <dd class="concept"><strong>
                        <div style="margin: 10px 0">
                        <%= f.label :コンセプト%>
                        <%=f.text_area :concept,class:"concept_input",placeholder: "ワークショップのコンセプト"%>
                        </strong>
                        </div>
                    </dd>

                    <div class="column_head_bottom">
                      <div class="tag_zone">
                      </div>
                    <div general_info>
                      <div class="general_info_left">
                          <div class="participants"><strong>
                              <div style="margin: 8px">
                              <%= f.label :対象の参加者%>
                               <%=f.text_field :participants,placeholder: "対象層"%>
                              </div></strong>
                          </div>
                          <div class="num_ppl"><strong>
                             <div style="margin: 8px">
                                 <%= f.label :参加人数%>
                                 <%=f.text_field :num_ppl,placeholder:"参加人数"%>
                                 </div></strong>
                          </div>
                          <div class="span">
                                <div style="margin: 8px">
                                    <%= f.label :期間%>
                                    <%=f.text_field :span%>
                               </div>
                          </div>

                      </div>
                      <div class="general_info_right">
                       <div class="facilitator"><strong>
                               <div style="margin: 8px">
                                <%= f.label :ファシリテーター%>
                                <%=f.text_field :facilitator%>
                                </div>
                       </strong><%=@seminar.facilitator%></div>
                        <div>
                        </div>
                      </div>
                      </div>
                        </div>
                      </div>

                    </div>
                    </div>

          <div class="widegets">
                <div class="info">
                <h3 class="side-header">
                    <%= f.label :タイムテーブル%>
                    <%=f.text_area :time_table, class:"time"%>
                </h3>
                </div>
           <div class="remark_tag">
                <h3 class="side-header">
              </div>
          </div>

                  <div class="seminar_detail clearfix">
                  <div class="intro_container">
                      <h2 id="intro"><span class="label label-warning">Introduction</span></h2>
                      <div>
                           <div class="title">
                                <div class="title_input"><%=f.text_field :intro_title, placeholder:"導入活動のタイトル" %></div>
                           </div>
                          </div>
                      <div class="main"><strong>
                           <div style="margin: 8px">
                            <%=f.text_area :intro, class:"intro",placeholder:"導入活動の詳細"%>
                            </div>
                      </strong>
                      </div>
                  </div>

                  <div class="body_container">
                      <h2 id="body"><span class="label label-success">Body</span></h2>
                          <div class="title">
                          <div class="title_input">
                            <%=f.text_field :body_title, placeholder:"メインパートのタイトル"%>
                        </div>
                          </div>
                      <div class="main">
                            <div style="margin: 8px">
                            <%=f.text_area :body,class:"intro",placeholder:"メインパートの詳細"%>
                            </div>
                      </div>
                      </div>

                  <div class="ending_container">
                      <h2 id="end"><span class="label label-primary">ending</span></h2>
                          <div class="title">
                          <div class="title_input">
                              <%=f.text_field :ending_title, placeholder:"エンディングのタイトル"%>
                          </div>
                          </div>
                      <div class="main">
                         <div style="margin: 8px">
                          <%=f.text_area :ending,class:"intro",placeholder:"エンディングパートの詳細"%>
                          </div>
                      </div>
                  </div>
              </div>



      </div>
  </div>
          </div>

    <div style="submit_btn">
        <%= f.submit "送信", class:"btn_input btn-primary withripple"%>
    </div>

      <% end %>
  </div>
</div>

</body>

app/views/seminars/search.html.erb
<body background="../assets/paper_tex.jpg">

        <div style="text-align: right">
        <a href="/seminars">ワークショップ一覧に戻る</a>
        </div>

          <article class="section">
            <div class="container">
              <header class="header header--section">
              </header>

              <form accept-charset="utf-8" action="/" class="js-search-submit" method="get">
              </form>
            </div>
          </article>
          <article class="section">
            <div class="container">
              <header class="header header--section">
                <h2 class="text-middle">
                   <h3 class="page-header"><strong>Search result</strong><br />検索結果</h3><p>
                </h2>
              </header>
            </div>
          </article>

  <div class="contentsset clearfix">
    <div class="articles">
        <% @seminar.each do |seminar| %>
          <%= render partial:"search_result", locals:{ seminar:seminar}%><%end%>
      </div>
      <div class="widegets">
          <div class="info">
          <h3 class="side-header"><strong>Information</strong><br />~お知らせ~</h3>
        <% @seminar.each do |seminar| %>
          <%= render partial:"information", locals:{ seminar:seminar}%><%end%>
          </div>
          <div class="remark_tag">
          <h3 class="side-header">
              <strong>Hot Keywords</strong><br />~注目のキーワード~</h3>
          </div>
          </div>
      </div>
    <%= paginate(@seminar) %>
  </div>

</body>

app/views/seminars/show.html.erb
<body background="../assets/paper_tex.jpg">
 <div id="main_cnt_wrapper">
    <div id="yjContentsBdy">
      <div class="yjContainer">
        <span class="yjGuid"><a id="yjContentsStart" name="yjContentsStart"></a><img alt="ここから本文です" height="1" src="http://i.yimg.jp/yui/jp/tmpl/1.1.0/audionav.gif" width="1"></span>
        <div style="text-align: right">
        <a href="/seminars">ワークショップ一覧に戻る</a>
       </div>


            <div class="container clearfix">
              <div class="contentsset">
                <div class="column_head">
                    <h3 class="page-header"><i><strong>ワークショップの概要!!!</strong></i></h3>
                    <div class="article_seminar">
                    <div class="seminar_title"><h1><%= @seminar.title%></div></h1><p class="timestamp"><%= @seminar.created_at%><br /></p>
                    <div class="seminar_photo"><div class="photo_all"><%= image_tag @seminar.photo_file_name%>
                    </div>
                    <dd class="concept"><strong>コンセプト:</strong><%= @seminar.concept%></dd>

                    <div class="column_head_bottom">
                      <div class="tag_zone">
                      </div>
                      <div class="general_info">
                          <div class="participants"><strong>参加した人々:<%=@seminar.participants%></strong></div>
                          <div class="num_ppl"><strong>参加人数:</strong><%=@seminar.num_ppl%></div>
                          <div class="span"><strong>期間:</strong><%=@seminar.span%></div>
                          <div class="facilitator"><strong>ファシリテーター:</strong><%=@seminar.facilitator%></div>
                      </div>
                        </div>
                      </div>
                    </div>
                    </div>


                  <div class="seminar_detail clearfix">
                  <div class="intro_container">
                      <h2 id="intro"><span class="label label-warning">Introduction</span></h2>
                      <div class="title_head">
                           <div class="title"><strong><%=@seminar.intro_title%></strong></div>
                          </div>
                      <div class="main"><strong><%=@seminar.intro%></strong>
                      </div>
                  </div>

                  <div class="body_container">
                      <h2 id="body"><span class="label label-success">Body</span></h2>
                          <div class="title_head">
                          <div class="title"><strong><%=@seminar.body_title%></strong></div>
                          </div>
                      <div class="main"><strong><%=@seminar.body%></strong></div>
                      </div>

                  <div class="ending_container">
                      <h2 id="end"><span class="label label-primary">ending</span></h2>
                          <div class="title_head">
                          <div class="title"><strong><%=@seminar.ending%></strong></div>
                          </div>
                      <div class="main"><strong><%=@seminar.ending%></strong></div>
                  </div>

                <div class="text-middle">
                  <h1 class="comments">みんなのレビュー</h1>
                    <% if @articles %>
                      <% @articles.each do |article| %>
                      <div class="comments">
                        <div class="comment_ind">
                          <div class="comment_title">
                          <h3><%= @name.nickname%></h3>
                          </div>
                          <div class="comment_cont">
                          <%= article.comment %>
                          </div>
                           </div>
                        </div>
                        <% end %>
                      <% end %>
                      </div>

                  <%= form_for [@seminar,@article],method: :post do |f| %>
                  <div style="margin: 8px 0">
                            <%= f.text_area :comment, placeholder: 'comments', style: 'width: 667px ;height: 100px;',id: "comment_field" %>
                            </div>
                            <div style="margin: 8px 0">
                            <% f.submit :article, class: "btn btn-primary"%>
                            <%= submit_tag "投稿",name: "btn btn--block"%>
                            </div>
                  <% end %>
                  </div>

              <footer>
              <div class="header header--section">
              </div>
            <div>
                      </div>
           </div>
              </footer>
           </div>
          </div>
        </div>
      </div>
</div>
</div>
</body>